@Host= http://localhost:5264

POST {{Host}}/api/quiz
Content-Type: application/json

{
    "title":"Quiz 2",
    "description": "Full quiz part",
    "state": 1,
    "StartsAt":"2025-08-01T12:00:00+05:00",
    "EndsAt":"2025-08-01T12:00:00+05:00",
    "IsPrivate":true
}
###
GET {{Host}}/api/quiz
###
GET {{Host}}/api/quiz/3
###
PUT  {{Host}}/api/quiz/2
Content-Type: application/json

{
    "title":"updated quiz 2",
    "description": "Full quiz part",
    "state": 0
}





