@Host = http://localhost:5226

POST {{Host}}/api/quiz
Content-Type: application/json

{
    "title": "Test quiz 1",
    "description": "Bu test quiz",
    "state": "disabled"
}
###

GET {{Host}}/api/quiz
###

GET {{Host}}/api/quiz/4
###

PUT {{Host}}/api/quiz/7
Content-Type: application/json

{
    "title": "Test quiz 3",
    "description": "Bu test quiz",
    "state": "deleted"
}
###
