@Host = http://localhost:5226

POST {{Host}}/api/quiz
Content-Type: application/json

{
    "title": "Test quiz 1",
    "description": "Bu test quiz",
    "state": "disabled"
}
###

GET {{Host}}/api/quiz
###

GET {{Host}}/api/quiz/1
###

PUT {{Host}}/api/quiz/1
Content-Type: application/json

{
    "title": "Test quiz 2",
    "description": "Bu test quiz",
    "state": "active"
}
###
